In [96]:
import pandas as pd
import numpy as np
from sklearn.metrics import precision_recall_fscore_support

In [97]:
unprunedAndImputedData = pd.read_csv('/home/vignesh/Downloads/Unprunued_and_Imputed_Training data.csv')
prunedData = pd.read_csv('/home/vignesh/Downloads/Final_dataset.csv')
testData = pd.read_csv('/home/vignesh/Downloads/Final_dataset_test.csv')

In [98]:
len(unprunedAndImputedData)

33849

In [99]:
def str_to_numeric(data1):
    label_mapping = {}
    char_cols = data1.dtypes.pipe(lambda x: x[x == 'object']).index
    for c in char_cols:
       data1[c], label_mapping[c] = pd.factorize(data1[c])
    return data1

In [100]:
unprunedAndImputedDataNumeric = str_to_numeric(unprunedAndImputedData)
prunedDataNumeric = str_to_numeric(prunedData)
testDataNumeric = str_to_numeric(testData)

In [153]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
X = unprunedAndImputedDataNumeric.drop(unprunedAndImputedDataNumeric.columns[0],axis=1).drop(['id','y','duration','nr.employed','default'],axis=1)
Y = unprunedAndImputedDataNumeric['y']
clf.fit(X,Y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [154]:
from sklearn.cross_validation import KFold
from sklearn.metrics import precision_score,f1_score
kf = KFold(len(Y), n_folds=4)
for train_index, test_index in kf:

   X_train, X_test = X.iloc[train_index], X.iloc[test_index]
   y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]

   clf.fit(X_train, y_train)
   y_pred = clf.predict(X_test) 
   tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
   specificity = tn / (tn+fp) 
   print("specificity = ",specificity) 
   print("precision = ",precision_score(y_test, y_pred))
   print("f1 score = ",f1_score(y_test, y_pred)) 
   print(confusion_matrix(y_test, y_pred))

specificity =  0.997799511002445
precision =  0.05263157894736842
f1 score =  0.006622516556291391
[[8162   18]
 [ 282    1]]
specificity =  0.9968501952878922
precision =  0.13793103448275862
f1 score =  0.01444043321299639
[[7912   25]
 [ 521    4]]
specificity =  0.9714398008646665
precision =  0.2482758620689655
f1 score =  0.128686327077748
[[7415  218]
 [ 757   72]]
specificity =  0.9829073482428115
precision =  0.6205673758865248
f1 score =  0.14090177133655393
[[6153  107]
 [2027  175]]


In [127]:
pred = clf.predict(
            testDataNumeric.drop(testDataNumeric.columns[0],axis=1).drop(['id','y','default'],axis=1),
           )

In [128]:
clf.score(testDataNumeric.drop(testDataNumeric.columns[0],axis=1).drop(['id','y','default'],axis=1),np.array(testDataNumeric['y']))

0.9001226325112414

In [129]:
pred = clf.predict(testDataNumeric.drop(testDataNumeric.columns[0],axis=1).drop(['id','y','default'],axis=1))

In [130]:
y_pred = pd.Series(pred, name="predicted")
y_actual = pd.Series(testData['y'], name="actual")
pd.crosstab(y_pred,y_actual)

actual        0    1
predicted           
0          6423  647
1            86  183

[[6558    1]
 [ 210    1]]
[[6390    7]
 [ 373    0]]
[[6375    7]
 [ 387    1]]
[[5972   42]
 [ 744   12]]
[[4608   50]
 [2029   82]]


In [ ]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(clf, unprunedAndImputedDataNumeric.drop(unprunedAndImputedDataNumeric.columns[0],axis=1).drop(['id','y','duration','nr.employed','default'],axis=1),
                           unprunedAndImputedDataNumeric['y'], cv=5)
conf_mat = confusion_matrix(unprunedAndImputedDataNumeric['y'], y_pred)

In [145]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=50, max_depth=None,min_samples_split=2, random_state=0)
X = prunedDataNumeric.drop(prunedDataNumeric.columns[0],axis=1).drop(['id','y','default','outliers'],axis=1)
Y = prunedDataNumeric['y']
# clf.fit(
#         prunedDataNumeric.drop(prunedDataNumeric.columns[0],axis=1).drop(['id','y','default','outliers'],axis=1),
#         prunedDataNumeric['y']
#        )

In [152]:
from sklearn.cross_validation import KFold
from sklearn.metrics import precision_score,f1_score
kf = KFold(len(Y), n_folds=4)
for train_index, test_index in kf:

   X_train, X_test = X.iloc[train_index], X.iloc[test_index]
   y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]

   clf.fit(X_train, y_train)
   y_pred = clf.predict(X_test) 
   tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
   specificity = tn / (tn+fp) 
   print("specificity = ",specificity) 
   print("precision = ",precision_score(y_test, y_pred))
   print("f1 score = ",f1_score(y_test, y_pred)) 
   print(confusion_matrix(y_test, y_pred))

specificity =  0.9772477640043935
precision =  0.6174142480211082
f1 score =  0.4031007751937985
[[6228  145]
 [ 548  234]]
specificity =  0.9721439749608763
precision =  0.5424164524421594
f1 score =  0.36568457538994803
[[6212  178]
 [ 554  211]]
specificity =  0.9683159044794756
precision =  0.5155131264916468
f1 score =  0.37017994858611825
[[6204  203]
 [ 532  216]]
specificity =  0.9672670321064996
precision =  0.5446623093681917
f1 score =  0.4071661237785016
[[6176  209]
 [ 519  250]]


In [144]:
for i in kf:
    print(i)

(array([ 7155,  7156,  7157, ..., 28616, 28617, 28618]), array([   0,    1,    2, ..., 7152, 7153, 7154]))
(array([    0,     1,     2, ..., 28616, 28617, 28618]), array([ 7155,  7156,  7157, ..., 14307, 14308, 14309]))
(array([    0,     1,     2, ..., 28616, 28617, 28618]), array([14310, 14311, 14312, ..., 21462, 21463, 21464]))
(array([    0,     1,     2, ..., 21462, 21463, 21464]), array([21465, 21466, 21467, ..., 28616, 28617, 28618]))


In [92]:
clf.score(testDataNumeric.drop(testDataNumeric.columns[0],axis=1).drop(['id','y','default'],axis=1),np.array(testDataNumeric['y']))

0.897261207248944

In [93]:
pred = clf.predict(testDataNumeric.drop(testDataNumeric.columns[0],axis=1).drop(['id','y','default'],axis=1))

In [94]:
y_pred = pd.Series(pred, name="predicted")
y_actual = pd.Series(testData['y'], name="actual")
pd.crosstab(y_pred,y_actual)

actual        0    1
predicted           
0          6403  648
1           106  182

In [75]:
len(prunedData[prunedData['y']==1])

25629

In [80]:
len(unprunedAndImputedDataNumeric[unprunedAndImputedDataNumeric['y']==1])

3839

In [47]:
unprunedAndImputedDataNumeric.drop(unprunedAndImputedDataNumeric.columns[0],axis=1).drop(['id','y','duration','nr.employed','default'],axis=1).columns

Index(['age', 'job', 'marital', 'education', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m'],
      dtype='object')

In [48]:
len(prunedDataNumeric)

28617

In [49]:
testData

Unnamed: 0  age  job  marital  education  default  housing  loan  \
0            554   56    0        0          0        0        0     0   
1          19765   32    1        1          1        0        0     1   
2          34726   75    0        0          0        0        1     1   
3          28116   50    2        0          2        0        1     1   
4           6189   46    3        1          3        0        0     1   
5          34488   86    0        2          0        0        0     1   
6          31221   22    3        1          3        0        0     1   
7           5710   31    3        1          3        0        0     1   
8          19753   33    1        0          4        0        1     1   
9          15188   50    4        0          2        0        1     1   
10         33002   33    3        0          1        0        0     1   
11         17883   30    2        0          2        0        1     1   
12         31632   28    5        1          4        0        0     1   
13          8072   35    2        0          0        0        1     1   
14         13436   34    1        0          3        0        0     0   
15         14680   30    2        0          2        0        0     1   
16         29207   48    2        0          2        0        0     1   
17          3578   33    2        1          2        0        0     1   
18         29398   58    0        0          2        0        1     0   
19         33830   56    0        0          3        0        0     0   
20          8786   39    6        1          5        0        1     1   
21          3004   29    3        1          1        0        0     0   
22         36109   31    7        1          1        0        0     1   
23         19319   31    3        0          3        0        1     1   
24           221   58    0        0          1        0        1     1   
25         36296   45    2        1          3        0        0     0   
26         24279   41    4        0          2        0        0     1   
27         32839   32    2        1          3        0        1     1   
28         23033   46    3        0          1        0        0     1   
29         20290   53    2        0          0        0        0     1   
...          ...  ...  ...      ...        ...      ...      ...   ...   
7309       19652   53    2        0          0        0        0     1   
7310       14941   27    2        0          2        0        1     0   
7311       15868   37    3        0          1        0        0     1   
7312       17309   37    3        0          1        0        1     1   
7313       13194   30    3        0          1        0        1     1   
7314       22023   52    3        0          1        0        0     1   
7315        5782   47    1        1          1        0        0     0   
7316       36112   25    7        1          3        0        0     1   
7317        4955   57    2        0          0        0        0     1   
7318       17969   39    1        0          1        0        0     0   
7319       34018   72    0        2          0        0        1     1   
7320        9095   43    2        0          2        0        0     1   
7321       27117   51    3        2          4        0        1     0   
7322       25520   40    5        1          5        0        1     1   
7323       35143   43    3        0          3        0        0     1   
7324        6753   39    3        0          1        0        0     1   
7325       16267   28    3        1          1        0        0     1   
7326       31618   28    2        0          2        0        0     1   
7327       21906   37    1        1          4        0        0     1   
7328        7144   46    2        0          5        0        0     1   
7329       35995   51    3        0          1        0        1     0   
7330       35620   63    0        0          4        0        0     0   
7331      

In [70]:
temp = pd.read_csv('/home/vignesh/Downloads/cleaned_and_imputed_data.csv')
len(temp[temp['y']=='no'])

32677

In [71]:
prunedData

Unnamed: 0  age  job  marital  education  default  housing  loan  \
0           27445   30    0        1          0        0        0     0   
1           17409   34    0        1          0        0        1     1   
2            2547   25    1        0          0        0        0     0   
3           18632   49    2        1          1        0        1     1   
4           11068   38    3        1          2        0        0     0   
5           12137   50    3        1          3        0        0     1   
6           19440   52    2        1          1        0        1     0   
7           16136   29    3        0          4        0        0     0   
8           11540   34    4        1          5        0        0     0   
9           20266   35    2        1          5        0        0     1   
10          12767   43    2        0          1        0        1     0   
11          19939   33    2        0          5        0        1     1   
12          31729   42    3        1          3        0        0     0   
13            956   34    3        1          2        0        1     0   
14          35747   39    2        1          0        0        1     0   
15           2364   37    4        1          5        0        1     0   
16          29218   26    6        0          5        0        1     0   
17           3763   36    2        1          4        0        0     0   
18          35791   27    2        0          1        0        0     0   
19           7589   47    0        1          2        0        1     0   
20          12994   42    2        1          5        0        1     0   
21          32729   27    0        0          0        0        0     0   
22          15513   29    4        0          1        0        1     0   
23           4625   42    0        1          5        0        1     0   
24           1066   42    4        1          5        0        0     0   
25          13164   39    5        2          3        0        1     1   
26           4341   60    4        1          3        0        0     0   
27          22168   38    0        2          0        0        1     0   
28          22811   50    3        1          1        0        1     1   
29          28655   81    7        1          1        0        1     0   
...           ...  ...  ...      ...        ...      ...      ...   ...   
28587       34498   32    0        1          0        0        1     1   
28588       18394   34    4        1          5        0        1     0   
28589       14055   22    3        0          4        0        1     0   
28590       25616   32    8        1          0        0        0     0   
28591        4545   42    0        0          4        0        0     1   
28592       29402   39    3        0          3        0        0     0   
28593       25373   56    8        1          0        0        0     0   
28594        9115   34    3        1          3        0        0     0   
28595       17627   40    0        2          0        0        1     0   
28596       17298   49    2        0          0        0        0     0   
28597        8769   35    0        0          3        0        0     0   
28598       31753   42    2        1          1        0        1     0   
28599       15193   24    3        0          5        0        1     0   
28600       28291   24    0        0          0        0        1     0   
28601       28581   44    0        1          0        0        0     0   
28602         239   34    4        0          4        0        0     0   
28603        9645   36    4        2          0        0        0     0   
28604       31745   41    0        2          5        0        1     1   
28605       16950   54   10        1          5        0        0     0   
28606        1780   30    2        1          0        0        0     0   
28607        2460   36    0        1          0        0        0     0   
28608       19220   32    2     